### ISSUE TITLE
ELSE should use major-mode variable instead of mode-name variable

### ISSUE THREAD

**Issue by jschaf** [peter-milliken/ELSE#4]
The `major-mode` variable isn't usually overridden.  The `mode-name` variable is often overridden, usually to reduce noise in the mode-line.

ELSE should use the major-mode variable to select templates since it's much less likely to be changed.

**Comment by peter-milliken** [comment]
OK, I see what you are saying. Let me make sure I'm getting this right. This would mean we don't need to "translate" C++/l to C++ (for instance), it would just be C++-mode to C++?
What do you mean by "the `major-mode` variable isn't _usually_ overridden"? Does this mean it is (sometimes) overridden? If it is, does this remove the issue that else-Alternate-mode-names resolves? In fact, we could remove else-Alternate-mode-names altogether? Or would there still be a need for this variable?

**Comment by jschaf** [comment]
> This would mean we don't need to "translate" C++/l to C++ (for instance), it would just be C++-mode to C++

Yes, the `major-mode` variable is created by `define-derived-mode`.  So, it's consistent between all files that use that major-mode.

> What do you mean by "the major-mode variable isn't usually overridden"?

Mostly hedging my bets because since it's elisp, it is in fact possible to change anything.  However, it would be exceptionally weird to redefine the major-mode variable.   It's likely to break much functionality.  I'll experiment later.

> In fact, we could remove else-Alternate-mode-names altogether?

Most likely yes.  I'll take a look at how yasnippet does it.  Another option is to move the abstraction into a function but that feels slightly overkill

**Comment by peter-milliken** [comment]
ELSE now uses major mode name and change merged to master.
